# Generated by Django 3.2.24 on 2024-02-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rakernis_psm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_pelaksana', models.CharField(max_length=30)),
                ('satker_bnnp_bnnk_diundang', models.CharField(max_length=30)),
                ('deskripsi_hasil', models.TextField(max_length=100)),
                ('rekomendasi', models.TextField(max_length=100)),
                ('hambatan_kendala', models.TextField(max_length=100)),
                ('tanggal', models.DateTimeField()),
                ('kesimpulan', models.TextField(max_length=100)),
                ('dokumentasi', models.FileField(upload_to='upload/files/psm/rakernis/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rakernis_id_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
