# Generated by Django 4.1.7 on 2024-03-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_dayatif_bimbingan_teknis_lifeskill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DAYATIF_BIMBINGAN_TEKNIS_LIFESKILL',
        ),
        migrations.DeleteModel(
            name='DAYATIF_BIMBINGAN_TEKNIS_STAKEHOLDER',
        ),
        migrations.DeleteModel(
            name='DAYATIF_BINAAN_TEKNIS',
        ),
        migrations.DeleteModel(
            name='DAYATIF_DUKUNGAN_STAKEHOLDER',
        ),
        migrations.DeleteModel(
            name='DAYATIF_MONITORING_DAN_EVALUASI',
        ),
        migrations.DeleteModel(
            name='DAYATIF_PEMETAAN_POTENSI',
        ),
        migrations.DeleteModel(
            name='DAYATIF_PEMETAAN_STAKEHOLDER',
        ),
        migrations.DeleteModel(
            name='DAYATIF_RAPAT_SINERGI_STAKEHOLDER',
        ),
    ]
