# Generated by Django 4.1.7 on 2024-03-17 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0003_delete_dayatif_bimbingan_teknis_lifeskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAYATIF_BIMBINGAN_TEKNIS_LIFESKILL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_BIMBINGAN_TEKNIS_STAKEHOLDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_BINAAN_TEKNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_binaan_teknis_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_binaan_teknis_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_binaan_teknis_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAYATIF BINAAN TEKNIS',
                'verbose_name_plural': 'DAFTAR DAYATIF BINAAN TEKNIS',
                'db_table': 'kegiatan_dayatif_binaan_teknis',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DAYATIF_DUKUNGAN_STAKEHOLDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_MONITORING_DAN_EVALUASI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_PEMETAAN_POTENSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_PEMETAAN_STAKEHOLDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DAYATIF_RAPAT_SINERGI_STAKEHOLDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PSM_RAKERNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_rakernis_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_rakernis_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_rakernis_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM RAKERNIS',
                'verbose_name_plural': 'DAFTAR PSM RAKERNIS',
                'db_table': 'kegiatan_psm_rakernis',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='rakernis_psm',
        ),
    ]
