# Generated by Django 3.2.24 on 2024-03-17 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0005_alter_dayatif_bimbingan_teknis_lifeskill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAYATIF_KEGIATAN_BINAAN_TEKNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Kegiatan')),
                ('tanggal_akhir', models.DateField(verbose_name='Tanggal Akhir Kegiatan')),
                ('jumlah_hari_pelaksanaan', models.IntegerField(default=2, verbose_name='Jumlah Hari Pelaksanaan Kegiatan')),
                ('jumlah_peserta', models.IntegerField(verbose_name='Jumlah Peserta Kegiatan')),
                ('tujuan', models.TextField(max_length=2000)),
                ('kendala', models.TextField(max_length=2000)),
                ('kesimpulan', models.TextField(max_length=2000)),
                ('tindak_lanjut', models.TextField(max_length=2000)),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/dayatif/binaan_teknis/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_binaan_teknis_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_list_binaan_teknis', to='kegiatan.dayatif_binaan_teknis')),
                ('satker_target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_kegiatan_binaan_teknis_satker', to='users.satker', verbose_name='SATUAN KERJA TARGET')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_binaan_teknis_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAYATIF KEGIATAN BINAAN TEKNIS',
                'verbose_name_plural': 'DAFTAR DAYATIF KEGIATAN BINAAN TEKNIS',
                'db_table': 'kegiatan_dayatif_kegiatan_binaan_teknis',
                'ordering': ['-updated_at'],
            },
        ),
    ]
