# Generated by Django 3.2.24 on 2024-03-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0006_dayatif_kegiatan_binaan_teknis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayatif_kegiatan_binaan_teknis',
            old_name='satker_target',
            new_name='satker',
        ),
        migrations.AlterField(
            model_name='dayatif_kegiatan_binaan_teknis',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_binaan_teknis', to='kegiatan.dayatif_binaan_teknis'),
        ),
    ]
