# Generated by Django 3.2.24 on 2024-03-17 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0007_auto_20240318_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_kegiatan_binaan_teknis',
            name='tanggal_mulai',
        ),
        migrations.AddField(
            model_name='dayatif_kegiatan_binaan_teknis',
            name='tanggal_awal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Awal Kegiatan'),
            preserve_default=False,
        ),
    ]
