# Generated by Django 4.1.7 on 2024-03-17 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0008_auto_20240318_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayatif_kegiatan_binaan_teknis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_binaan_teknis_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_kegiatan_binaan_teknis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_kegiatan_binaan_teknis_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
