# Generated by Django 3.2.24 on 2024-03-18 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        ('kegiatan', '0009_alter_dayatif_kegiatan_binaan_teknis_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayatif_binaan_teknis',
            options={'ordering': ['-updated_at'], 'verbose_name': 'DAYATIF KEGIATAN BINAAN TEKNIS', 'verbose_name_plural': 'DAFTAR DAYATIF KEGIATAN BINAAN TEKNIS'},
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='dokumentasi',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/kegiatan/dayatif/binaan_teknis/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='jumlah_hari_pelaksanaan',
            field=models.IntegerField(default=2, verbose_name='Jumlah Hari Pelaksanaan Kegiatan'),
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='jumlah_peserta',
            field=models.IntegerField(default=1, verbose_name='Jumlah Peserta Kegiatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='kendala',
            field=models.TextField(default='-', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='kesimpulan',
            field=models.TextField(default='-', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='satker_target',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_binaan_teknis_satker_target', to='users.satker', verbose_name='SATUAN KERJA TARGET'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='tanggal_akhir',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Akhir Kegiatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='tanggal_awal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Awal Kegiatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='tindak_lanjut',
            field=models.TextField(default='-', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='tujuan',
            field=models.TextField(default='-', max_length=2000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DAYATIF_KEGIATAN_BINAAN_TEKNIS',
        ),
    ]
