# Generated by Django 3.2.24 on 2024-03-18 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0012_dayatif_bimbingan_teknis_lifeskill_dayatif_bimbingan_teknis_lifeskill_peserta_dayatif_bimbingan_tekn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_akhir',
            field=models.DateField(default=datetime.date.today, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_awal',
            field=models.DateField(default=datetime.date.today, verbose_name='Tanggal Awal Kegiatan'),
        ),
    ]
