# Generated by Django 3.2.24 on 2024-03-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0014_auto_20240318_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_awal',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Awal Kegiatan'),
        ),
    ]
