# Generated by Django 3.2.24 on 2024-03-18 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0015_auto_20240318_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psm_rakernis',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PSM RAKERNIS', 'verbose_name_plural': 'DAFTAR PSM RAKERNIS'},
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_akhir',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_awal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan'),
        ),
        migrations.AlterModelTable(
            name='psm_rakernis',
            table='kegiatan_psm_rakernis',
        ),
    ]
