# Generated by Django 3.2.24 on 2024-03-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0018_delete_psm_rakernis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DAYATIF_BINAAN_TEKNIS',
        ),
    ]
