# Generated by Django 3.2.24 on 2024-03-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    # dependencies = [
    #     ('kegiatan', '0017_auto_20240318_1146'),
    # ]

    operations = [
        migrations.DeleteModel(
            name='PSM_RAKERNIS',
        ),
    ]
