from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

router = routers.DefaultRouter()
router.register(
    "tbl_asistensi_pelaksanaan_psm", api.tbl_asistensi_pelaksanaan_psmViewSet
)
router.register("tbl_asistensi_psm", api.tbl_asistensi_psmViewSet)
router.register("tbl_audiensi_pelaksanaan_psm", api.tbl_audiensi_pelaksanaan_psmViewSet)
router.register("tbl_audiensi_psm", api.tbl_audiensi_psmViewSet)
router.register(
    "tbl_bimbingan_teknis_life_skill_dayatif",
    api.tbl_bimbingan_teknis_life_skill_dayatifViewSet,
)
router.register(
    "tbl_bimbingan_teknis_life_skill_detail_dayatif",
    api.tbl_bimbingan_teknis_life_skill_detail_dayatifViewSet,
)
router.register(
    "tbl_bimtek_penggiat_p4gn_lingkungan_psm",
    api.tbl_bimtek_penggiat_p4gn_lingkungan_psmViewSet,
)
router.register("tbl_bimtek_penggiat_p4gn_psm", api.tbl_bimtek_penggiat_p4gn_psmViewSet)
router.register("tbl_bimtek_psm", api.tbl_bimtek_psmViewSet)
router.register(
    "tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm",
    api.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmViewSet,
)
router.register(
    "tbl_data_dukungan_stakeholder_psm", api.tbl_data_dukungan_stakeholder_psmViewSet
)
router.register(
    "tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif",
    api.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifViewSet,
)
router.register(
    "tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif",
    api.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifViewSet,
)
router.register(
    "tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif",
    api.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifViewSet,
)
router.register(
    "tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif",
    api.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifViewSet,
)
router.register(
    "tbl_kegiatan_lainnya_pelaksanaan_psm",
    api.tbl_kegiatan_lainnya_pelaksanaan_psmViewSet,
)
router.register("tbl_kegiatan_lainnya_psm", api.tbl_kegiatan_lainnya_psmViewSet)
router.register(
    "tbl_konsolidasi_kebijakan_pelaksanaan_psm",
    api.tbl_konsolidasi_kebijakan_pelaksanaan_psmViewSet,
)
router.register(
    "tbl_konsolidasi_kebijakan_psm", api.tbl_konsolidasi_kebijakan_psmViewSet
)
router.register(
    "tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif",
    api.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifViewSet,
)
router.register(
    "tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif",
    api.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifViewSet,
)
router.register(
    "tbl_monev_rangka_pendampingan_masyarakat_dayatif",
    api.tbl_monev_rangka_pendampingan_masyarakat_dayatifViewSet,
)
router.register(
    "tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif",
    api.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifViewSet,
)
router.register(
    "tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm",
    api.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmViewSet,
)
router.register(
    "tbl_monev_supervisi_kegiatan_kotan_psm",
    api.tbl_monev_supervisi_kegiatan_kotan_psmViewSet,
)
router.register(
    "tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif",
    api.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifViewSet,
)
router.register(
    "tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif",
    api.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifViewSet,
)
router.register(
    "tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif",
    api.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifViewSet,
)
router.register(
    "tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif",
    api.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifViewSet,
)
router.register(
    "tbl_pengumpulan_data_ikotan_pelaksanaan_psm",
    api.tbl_pengumpulan_data_ikotan_pelaksanaan_psmViewSet,
)
router.register(
    "tbl_pengumpulan_data_ikotan_psm", api.tbl_pengumpulan_data_ikotan_psmViewSet
)
router.register("tbl_rakernis_psm", api.tbl_rakernis_psmViewSet)
router.register(
    "tbl_rakor_pemetaan_pelaksanaan_psm", api.tbl_rakor_pemetaan_pelaksanaan_psmViewSet
)
router.register("tbl_rakor_pemetaan_psm", api.tbl_rakor_pemetaan_psmViewSet)
router.register(
    "tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif",
    api.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifViewSet,
)
router.register(
    "tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif",
    api.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifViewSet,
)
router.register(
    "tbl_rekapitulasi_pembinaan_teknis_dayatif",
    api.tbl_rekapitulasi_pembinaan_teknis_dayatifViewSet,
)
router.register(
    "tbl_rekapitulasi_pembinaan_teknis_detail_dayatif",
    api.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifViewSet,
)
router.register(
    "tbl_sinkronisasi_kebijakan_pelaksanaan_psm",
    api.tbl_sinkronisasi_kebijakan_pelaksanaan_psmViewSet,
)
router.register(
    "tbl_sinkronisasi_kebijakan_psm", api.tbl_sinkronisasi_kebijakan_psmViewSet
)
router.register(
    "tbl_tes_urine_deteksi_dini_pelaksanaan_psm",
    api.tbl_tes_urine_deteksi_dini_pelaksanaan_psmViewSet,
)
router.register(
    "tbl_tes_urine_deteksi_dini_psm", api.tbl_tes_urine_deteksi_dini_psmViewSet
)
router.register(
    "tbl_workshop_penggiat_pelaksanaan_psm",
    api.tbl_workshop_penggiat_pelaksanaan_psmViewSet,
)
router.register("tbl_workshop_penggiat_psm", api.tbl_workshop_penggiat_psmViewSet)
router.register(
    "tbl_workshop_tematik_pelaksanaan_psm",
    api.tbl_workshop_tematik_pelaksanaan_psmViewSet,
)
router.register("tbl_workshop_tematik_psm", api.tbl_workshop_tematik_psmViewSet)

# Router start here
urlpatterns = (
    # DAYATIF
    path(
        "dayatif/bintek/",
        views.dayatif_bintekView.as_view(),
        name="dayatif_bintek",
    ),
    path(
        "dayatif/bintek2/",
        views.dayatif_revisi_bintekView.as_view(),
        name="dayatif_bintek2",
    ),
    path(
        "dayatif/pemetaan_potensi/",
        views.dayatif_pemetaan_potensiView.as_view(),
        name="dayatif_pemetaan_potensi",
    ),
    path(
        "dayatif/pemetaan_stakeholder/",
        views.dayatif_pemetaan_stakeholderView.as_view(),
        name="dayatif_pemetaan_stakeholder",
    ),
    path(
        "dayatif/rapat_sinergi_stakeholder/",
        views.dayatif_rapat_sinergi_stakeholderView.as_view(),
        name="dayatif_rapat_sinergi_stakeholder",
    ),
    
    path(
        "dayatif/bimtek_stakeholder/",
        views.dayatif_bimtek_stakeholderView.as_view(),
        name="dayatif_bimtek_stakeholder",
    ),
    path(
        "dayatif/bimtek_lifeskill/",
        views.dayatif_bimtek_lifeskillView.as_view(),
        name="dayatif_bimtek_lifeskill",
    ),
    path(
        "dayatif/monev_dayatif/",
        views.dayatif_monev_dayatifView.as_view(),
        name="dayatif_monev_dayatif",
    ),
    path(
        "dayatif/monev_kewirausahaan_dan_ikkr/",
        views.dayatif_monev_kewirausahaan_dan_ikkrView.as_view(),
        name="dayatif_monev_kewirausahaan_dan_ikkr",
    ),
    path(
        "dayatif/monev_pendampingan/",
        views.dayatif_monev_pendampinganView.as_view(),
        name="dayatif_monev_pendampingan",
    ),
    path(
        "dayatif/data_dukungan_stakeholder/",
        views.dayatif_data_dukungan_stakeholderView.as_view(),
        name="dayatif_data_dukungan_stakeholder",
    ),
    path(
        "dayatif/dukungan_stakeholder/",
        views.dayatif_dukungan_stakeholderView.as_view(),
        name="dayatif_dukungan_stakeholder",
    ),
    # END

    # PSM
    path(
        "psm/rakernis/",
        views.psm_rakernisView.as_view(),
        name="psm_rakernis",
    ),
    path(
        "psm/bintek/",
        views.psm_bintekView.as_view(),
        name="psm_bintek",
    ),
    path(
        "psm/rakor_pemetaan/",
        views.psm_rakor_pemetaanView.as_view(),
        name="psm_rakor_pemetaan",
    ),
    path(
        "psm/rakor_pemetaan2/",
        views.psm_rakor_pemetaanView_2.as_view(),
        name="psm_rakor_pemetaan2",
    ),
    path(
        "psm/audiensi/",
        views.psm_audiensiView.as_view(),
        name="psm_audiensi",
    ),
    path(
        "psm/konsolidasi_kebijakan/",
        views.psm_konsolidasi_kebijakanView.as_view(),
        name="psm_konsolidasi_kebijakan",
    ),
    path(
        "psm/workshop_penggiat/",
        views.psm_workshop_penggiatView.as_view(),
        name="psm_workshop_penggiat",
    ),
    path(
        "psm/bintek_peggiat_p4gn/",
        views.psm_bintek_peggiat_p4gnView.as_view(),
        name="psm_bintek_peggian_p4gn",
    ),
    path(
        "psm/sinkronisasi_kebijakan/",
        views.psm_sinkronisasi_kebijakanView.as_view(),
        name="psm_sinkronisasi_kebijakan",
    ),
    path(
        "psm/workshop_tematik/",
        views.psm_workshop_tematikView.as_view(),
        name="psm_workshop_tematik",
    ),
    path(
        "psm/asistensi/",
        views.psm_asistensiView.as_view(),
        name="psm_asistensi",
    ),
    path(
        "psm/tes_urine/",
        views.psm_tes_urine_deteksi_diniView.as_view(),
        name="psm_tes_urine",
    ),
    path(
        "psm/monev_supervisi_kegiatan_kotan/",
        views.psm_monev_supervisi_kegiatan_kotanView.as_view(),
        name="psm_monev_supervisi_kegiatan_kotan",
    ),
    path(
        "psm/pengumpulan_data_ikotan/",
        views.psm_pengumpulan_data_ikotanView.as_view(),
        name="psm_pengumpulan_data_ikotan",
    ),
    path(
        "psm/dukungan_stakeholder/",
        views.psm_dukungan_stakeholderView.as_view(),
        name="psm_dukungan_stakeholder",
    ),
    path(
        "psm/kegiatan_lainnya/",
        views.psm_kegiatan_lainnyaView.as_view(),
        name="psm_kegiatan_lainnya",
    ),
    # END
    path("api/v1/", include(router.urls)),
    path(
        "pelaporan/tbl_asistensi_pelaksanaan_psm/",
        views.tbl_asistensi_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_asistensi_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_asistensi_pelaksanaan_psm/create/",
        views.tbl_asistensi_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_asistensi_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_asistensi_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_asistensi_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_asistensi_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_asistensi_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_asistensi_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_asistensi_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_asistensi_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_asistensi_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_asistensi_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_asistensi_psm/",
        views.tbl_asistensi_psmListView.as_view(),
        name="pelaporan_tbl_asistensi_psm_list",
    ),
    path(
        "pelaporan/tbl_asistensi_psm/create/",
        views.tbl_asistensi_psmCreateView.as_view(),
        name="pelaporan_tbl_asistensi_psm_create",
    ),
    path(
        "pelaporan/tbl_asistensi_psm/detail/<int:pk>/",
        views.tbl_asistensi_psmDetailView.as_view(),
        name="pelaporan_tbl_asistensi_psm_detail",
    ),
    path(
        "pelaporan/tbl_asistensi_psm/update/<int:pk>/",
        views.tbl_asistensi_psmUpdateView.as_view(),
        name="pelaporan_tbl_asistensi_psm_update",
    ),
    path(
        "pelaporan/tbl_asistensi_psm/delete/<int:pk>/",
        views.tbl_asistensi_psmDeleteView.as_view(),
        name="pelaporan_tbl_asistensi_psm_delete",
    ),
    path(
        "pelaporan/tbl_audiensi_pelaksanaan_psm/",
        views.tbl_audiensi_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_audiensi_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_audiensi_pelaksanaan_psm/create/",
        views.tbl_audiensi_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_audiensi_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_audiensi_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_audiensi_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_audiensi_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_audiensi_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_audiensi_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_audiensi_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_audiensi_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_audiensi_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_audiensi_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_audiensi_psm/",
        views.tbl_audiensi_psmListView.as_view(),
        name="pelaporan_tbl_audiensi_psm_list",
    ),
    path(
        "pelaporan/tbl_audiensi_psm/create/",
        views.tbl_audiensi_psmCreateView.as_view(),
        name="pelaporan_tbl_audiensi_psm_create",
    ),
    path(
        "pelaporan/tbl_audiensi_psm/detail/<int:pk>/",
        views.tbl_audiensi_psmDetailView.as_view(),
        name="pelaporan_tbl_audiensi_psm_detail",
    ),
    path(
        "pelaporan/tbl_audiensi_psm/update/<int:pk>/",
        views.tbl_audiensi_psmUpdateView.as_view(),
        name="pelaporan_tbl_audiensi_psm_update",
    ),
    path(
        "pelaporan/tbl_audiensi_psm/delete/<int:pk>/",
        views.tbl_audiensi_psmDeleteView.as_view(),
        name="pelaporan_tbl_audiensi_psm_delete",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_dayatif/",
        views.tbl_bimbingan_teknis_life_skill_dayatifListView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_dayatif_list",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_dayatif/create/",
        views.tbl_bimbingan_teknis_life_skill_dayatifCreateView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_dayatif_create",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_dayatif/detail/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_dayatifDetailView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_dayatif/update/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_dayatif_update",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_dayatif/delete/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_detail_dayatif/",
        views.tbl_bimbingan_teknis_life_skill_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_detail_dayatif/create/",
        views.tbl_bimbingan_teknis_life_skill_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_detail_dayatif/detail/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_detail_dayatif/update/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_bimbingan_teknis_life_skill_detail_dayatif/delete/<int:pk>/",
        views.tbl_bimbingan_teknis_life_skill_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_bimbingan_teknis_life_skill_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_lingkungan_psm/",
        views.tbl_bimtek_penggiat_p4gn_lingkungan_psmListView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_lingkungan_psm_list",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_lingkungan_psm/create/",
        views.tbl_bimtek_penggiat_p4gn_lingkungan_psmCreateView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_lingkungan_psm_create",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_lingkungan_psm/detail/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_lingkungan_psmDetailView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_lingkungan_psm_detail",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_lingkungan_psm/update/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_lingkungan_psmUpdateView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_lingkungan_psm_update",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_lingkungan_psm/delete/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_lingkungan_psmDeleteView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_lingkungan_psm_delete",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_psm/",
        views.tbl_bimtek_penggiat_p4gn_psmListView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_psm_list",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_psm/create/",
        views.tbl_bimtek_penggiat_p4gn_psmCreateView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_psm_create",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_psm/detail/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_psmDetailView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_psm_detail",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_psm/update/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_psmUpdateView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_psm_update",
    ),
    path(
        "pelaporan/tbl_bimtek_penggiat_p4gn_psm/delete/<int:pk>/",
        views.tbl_bimtek_penggiat_p4gn_psmDeleteView.as_view(),
        name="pelaporan_tbl_bimtek_penggiat_p4gn_psm_delete",
    ),
    path(
        "pelaporan/tbl_bimtek_psm/",
        views.tbl_bimtek_psmListView.as_view(),
        name="pelaporan_tbl_bimtek_psm_list",
    ),
    path(
        "pelaporan/tbl_bimtek_psm/create/",
        views.tbl_bimtek_psmCreateView.as_view(),
        name="pelaporan_tbl_bimtek_psm_create",
    ),
    path(
        "pelaporan/tbl_bimtek_psm/detail/<int:pk>/",
        views.tbl_bimtek_psmDetailView.as_view(),
        name="pelaporan_tbl_bimtek_psm_detail",
    ),
    path(
        "pelaporan/tbl_bimtek_psm/update/<int:pk>/",
        views.tbl_bimtek_psmUpdateView.as_view(),
        name="pelaporan_tbl_bimtek_psm_update",
    ),
    path(
        "pelaporan/tbl_bimtek_psm/delete/<int:pk>/",
        views.tbl_bimtek_psmDeleteView.as_view(),
        name="pelaporan_tbl_bimtek_psm_delete",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm/",
        views.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmListView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm_list",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm/create/",
        views.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmCreateView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm_create",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm/detail/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmDetailView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm_detail",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm/update/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmUpdateView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm_update",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm/delete/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psmDeleteView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_lingkup_kegiatan_p4gn_psm_delete",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_psm/",
        views.tbl_data_dukungan_stakeholder_psmListView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_psm_list",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_psm/create/",
        views.tbl_data_dukungan_stakeholder_psmCreateView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_psm_create",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_psm/detail/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_psmDetailView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_psm_detail",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_psm/update/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_psmUpdateView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_psm_update",
    ),
    path(
        "pelaporan/tbl_data_dukungan_stakeholder_psm/delete/<int:pk>/",
        views.tbl_data_dukungan_stakeholder_psmDeleteView.as_view(),
        name="pelaporan_tbl_data_dukungan_stakeholder_psm_delete",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifListView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif_list",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif/create/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifCreateView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif_create",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif/detail/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifDetailView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif/update/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif_update",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif/delete/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif/create/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif/detail/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif/update/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif/delete/<int:pk>/",
        views.tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_dukungan_stakeholder_dalam_pemberdayaan_alternatif_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifListView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif_list",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif/create/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifCreateView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif_create",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif/detail/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifDetailView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif/update/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif_update",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif/delete/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif/create/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif/detail/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif/update/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif/delete/<int:pk>/",
        views.tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_kegiatan_bimtek_stakeholder_pendamping_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_pelaksanaan_psm/",
        views.tbl_kegiatan_lainnya_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_pelaksanaan_psm/create/",
        views.tbl_kegiatan_lainnya_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_kegiatan_lainnya_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_kegiatan_lainnya_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_kegiatan_lainnya_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_psm/",
        views.tbl_kegiatan_lainnya_psmListView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_psm_list",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_psm/create/",
        views.tbl_kegiatan_lainnya_psmCreateView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_psm_create",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_psm/detail/<int:pk>/",
        views.tbl_kegiatan_lainnya_psmDetailView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_psm_detail",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_psm/update/<int:pk>/",
        views.tbl_kegiatan_lainnya_psmUpdateView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_psm_update",
    ),
    path(
        "pelaporan/tbl_kegiatan_lainnya_psm/delete/<int:pk>/",
        views.tbl_kegiatan_lainnya_psmDeleteView.as_view(),
        name="pelaporan_tbl_kegiatan_lainnya_psm_delete",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_pelaksanaan_psm/",
        views.tbl_konsolidasi_kebijakan_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_pelaksanaan_psm/create/",
        views.tbl_konsolidasi_kebijakan_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_psm/",
        views.tbl_konsolidasi_kebijakan_psmListView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_psm_list",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_psm/create/",
        views.tbl_konsolidasi_kebijakan_psmCreateView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_psm_create",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_psm/detail/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_psmDetailView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_psm_detail",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_psm/update/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_psmUpdateView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_psm_update",
    ),
    path(
        "pelaporan/tbl_konsolidasi_kebijakan_psm/delete/<int:pk>/",
        views.tbl_konsolidasi_kebijakan_psmDeleteView.as_view(),
        name="pelaporan_tbl_konsolidasi_kebijakan_psm_delete",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifListView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif_list",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif/create/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifCreateView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif_create",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif/detail/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifDetailView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif/update/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif_update",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif/delete/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif/create/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif/detail/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif/update/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif/delete/<int:pk>/",
        views.tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_monev_pemberdayaan_alternatif_kawasan_rawan_narkoba_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_dayatif/",
        views.tbl_monev_rangka_pendampingan_masyarakat_dayatifListView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_dayatif_list",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_dayatif/create/",
        views.tbl_monev_rangka_pendampingan_masyarakat_dayatifCreateView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_dayatif_create",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_dayatif/detail/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_dayatifDetailView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_dayatif/update/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_dayatif_update",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_dayatif/delete/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif/",
        views.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif/create/",
        views.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif/detail/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif/update/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif/delete/<int:pk>/",
        views.tbl_monev_rangka_pendampingan_masyarakat_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_monev_rangka_pendampingan_masyarakat_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm/",
        views.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm/create/",
        views.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_psm/",
        views.tbl_monev_supervisi_kegiatan_kotan_psmListView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_psm_list",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_psm/create/",
        views.tbl_monev_supervisi_kegiatan_kotan_psmCreateView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_psm_create",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_psm/detail/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_psmDetailView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_psm_detail",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_psm/update/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_psmUpdateView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_psm_update",
    ),
    path(
        "pelaporan/tbl_monev_supervisi_kegiatan_kotan_psm/delete/<int:pk>/",
        views.tbl_monev_supervisi_kegiatan_kotan_psmDeleteView.as_view(),
        name="pelaporan_tbl_monev_supervisi_kegiatan_kotan_psm_delete",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifListView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif_list",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif/create/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifCreateView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif_create",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif/detail/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifDetailView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif/update/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif_update",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif/delete/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif/create/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif/detail/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif/update/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif/delete/<int:pk>/",
        views.tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_pemetaan_potensi_sdm_dan_sda_kawasan_rawan_narkoba_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifListView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif_list",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif/create/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifCreateView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif_create",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif/detail/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifDetailView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif/update/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif_update",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif/delete/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif/create/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif/detail/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif/update/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif/delete/<int:pk>/",
        views.tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_pemetaan_stakeholder_pada_kawasan_rawan_narkoba_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_pelaksanaan_psm/",
        views.tbl_pengumpulan_data_ikotan_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_pelaksanaan_psm/create/",
        views.tbl_pengumpulan_data_ikotan_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_psm/",
        views.tbl_pengumpulan_data_ikotan_psmListView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_psm_list",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_psm/create/",
        views.tbl_pengumpulan_data_ikotan_psmCreateView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_psm_create",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_psm/detail/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_psmDetailView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_psm_detail",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_psm/update/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_psmUpdateView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_psm_update",
    ),
    path(
        "pelaporan/tbl_pengumpulan_data_ikotan_psm/delete/<int:pk>/",
        views.tbl_pengumpulan_data_ikotan_psmDeleteView.as_view(),
        name="pelaporan_tbl_pengumpulan_data_ikotan_psm_delete",
    ),
    path(
        "pelaporan/tbl_rakernis_psm/",
        views.tbl_rakernis_psmListView.as_view(),
        name="pelaporan_tbl_rakernis_psm_list",
    ),
    path(
        "pelaporan/tbl_rakernis_psm/create/",
        views.tbl_rakernis_psmCreateView.as_view(),
        name="pelaporan_tbl_rakernis_psm_create",
    ),
    path(
        "pelaporan/tbl_rakernis_psm/detail/<int:pk>/",
        views.tbl_rakernis_psmDetailView.as_view(),
        name="pelaporan_tbl_rakernis_psm_detail",
    ),
    path(
        "pelaporan/tbl_rakernis_psm/update/<int:pk>/",
        views.tbl_rakernis_psmUpdateView.as_view(),
        name="pelaporan_tbl_rakernis_psm_update",
    ),
    path(
        "pelaporan/tbl_rakernis_psm/delete/<int:pk>/",
        views.tbl_rakernis_psmDeleteView.as_view(),
        name="pelaporan_tbl_rakernis_psm_delete",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_pelaksanaan_psm/",
        views.tbl_rakor_pemetaan_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_pelaksanaan_psm/create/",
        views.tbl_rakor_pemetaan_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_rakor_pemetaan_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_rakor_pemetaan_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_rakor_pemetaan_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_psm/",
        views.tbl_rakor_pemetaan_psmListView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_psm_list",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_psm/create/",
        views.tbl_rakor_pemetaan_psmCreateView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_psm_create",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_psm/detail/<int:pk>/",
        views.tbl_rakor_pemetaan_psmDetailView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_psm/update/<int:pk>/",
        views.tbl_rakor_pemetaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_psm_update",
    ),
    path(
        "pelaporan/tbl_rakor_pemetaan_psm/delete/<int:pk>/",
        views.tbl_rakor_pemetaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_rakor_pemetaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifListView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif_list",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif/create/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifCreateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif_create",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif/detail/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifDetailView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif/update/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif_update",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif/delete/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif/create/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif/detail/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif/update/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif/delete/<int:pk>/",
        views.tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_rekapitulasi_kegiatan_rapat_kerja_sinergi_stakeholder_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_dayatif/",
        views.tbl_rekapitulasi_pembinaan_teknis_dayatifListView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_dayatif_list",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_dayatif/create/",
        views.tbl_rekapitulasi_pembinaan_teknis_dayatifCreateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_dayatif_create",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_dayatif/detail/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_dayatifDetailView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_dayatif/update/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_dayatif_update",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_dayatif/delete/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_detail_dayatif/",
        views.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifListView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_detail_dayatif_list",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_detail_dayatif/create/",
        views.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifCreateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_detail_dayatif_create",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_detail_dayatif/detail/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifDetailView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_detail_dayatif_detail",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_detail_dayatif/update/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifUpdateView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_detail_dayatif_update",
    ),
    path(
        "pelaporan/tbl_rekapitulasi_pembinaan_teknis_detail_dayatif/delete/<int:pk>/",
        views.tbl_rekapitulasi_pembinaan_teknis_detail_dayatifDeleteView.as_view(),
        name="pelaporan_tbl_rekapitulasi_pembinaan_teknis_detail_dayatif_delete",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_pelaksanaan_psm/",
        views.tbl_sinkronisasi_kebijakan_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_pelaksanaan_psm/create/",
        views.tbl_sinkronisasi_kebijakan_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_psm/",
        views.tbl_sinkronisasi_kebijakan_psmListView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_psm_list",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_psm/create/",
        views.tbl_sinkronisasi_kebijakan_psmCreateView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_psm_create",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_psm/detail/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_psmDetailView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_psm_detail",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_psm/update/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_psmUpdateView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_psm_update",
    ),
    path(
        "pelaporan/tbl_sinkronisasi_kebijakan_psm/delete/<int:pk>/",
        views.tbl_sinkronisasi_kebijakan_psmDeleteView.as_view(),
        name="pelaporan_tbl_sinkronisasi_kebijakan_psm_delete",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_pelaksanaan_psm/",
        views.tbl_tes_urine_deteksi_dini_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_pelaksanaan_psm/create/",
        views.tbl_tes_urine_deteksi_dini_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_psm/",
        views.tbl_tes_urine_deteksi_dini_psmListView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_psm_list",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_psm/create/",
        views.tbl_tes_urine_deteksi_dini_psmCreateView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_psm_create",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_psm/detail/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_psmDetailView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_psm_detail",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_psm/update/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_psmUpdateView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_psm_update",
    ),
    path(
        "pelaporan/tbl_tes_urine_deteksi_dini_psm/delete/<int:pk>/",
        views.tbl_tes_urine_deteksi_dini_psmDeleteView.as_view(),
        name="pelaporan_tbl_tes_urine_deteksi_dini_psm_delete",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_pelaksanaan_psm/",
        views.tbl_workshop_penggiat_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_pelaksanaan_psm/create/",
        views.tbl_workshop_penggiat_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_workshop_penggiat_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_workshop_penggiat_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_workshop_penggiat_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_psm/",
        views.tbl_workshop_penggiat_psmListView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_psm_list",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_psm/create/",
        views.tbl_workshop_penggiat_psmCreateView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_psm_create",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_psm/detail/<int:pk>/",
        views.tbl_workshop_penggiat_psmDetailView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_psm_detail",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_psm/update/<int:pk>/",
        views.tbl_workshop_penggiat_psmUpdateView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_psm_update",
    ),
    path(
        "pelaporan/tbl_workshop_penggiat_psm/delete/<int:pk>/",
        views.tbl_workshop_penggiat_psmDeleteView.as_view(),
        name="pelaporan_tbl_workshop_penggiat_psm_delete",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_pelaksanaan_psm/",
        views.tbl_workshop_tematik_pelaksanaan_psmListView.as_view(),
        name="pelaporan_tbl_workshop_tematik_pelaksanaan_psm_list",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_pelaksanaan_psm/create/",
        views.tbl_workshop_tematik_pelaksanaan_psmCreateView.as_view(),
        name="pelaporan_tbl_workshop_tematik_pelaksanaan_psm_create",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_pelaksanaan_psm/detail/<int:pk>/",
        views.tbl_workshop_tematik_pelaksanaan_psmDetailView.as_view(),
        name="pelaporan_tbl_workshop_tematik_pelaksanaan_psm_detail",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_pelaksanaan_psm/update/<int:pk>/",
        views.tbl_workshop_tematik_pelaksanaan_psmUpdateView.as_view(),
        name="pelaporan_tbl_workshop_tematik_pelaksanaan_psm_update",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_pelaksanaan_psm/delete/<int:pk>/",
        views.tbl_workshop_tematik_pelaksanaan_psmDeleteView.as_view(),
        name="pelaporan_tbl_workshop_tematik_pelaksanaan_psm_delete",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_psm/",
        views.tbl_workshop_tematik_psmListView.as_view(),
        name="pelaporan_tbl_workshop_tematik_psm_list",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_psm/create/",
        views.tbl_workshop_tematik_psmCreateView.as_view(),
        name="pelaporan_tbl_workshop_tematik_psm_create",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_psm/detail/<int:pk>/",
        views.tbl_workshop_tematik_psmDetailView.as_view(),
        name="pelaporan_tbl_workshop_tematik_psm_detail",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_psm/update/<int:pk>/",
        views.tbl_workshop_tematik_psmUpdateView.as_view(),
        name="pelaporan_tbl_workshop_tematik_psm_update",
    ),
    path(
        "pelaporan/tbl_workshop_tematik_psm/delete/<int:pk>/",
        views.tbl_workshop_tematik_psmDeleteView.as_view(),
        name="pelaporan_tbl_workshop_tematik_psm_delete",
    ),
)
